import faq_img1 from "./../images/image 8.png";
import threedimg1 from './../images/Rectangle 643 (2).png'
import threedimg2 from './../images/Rectangle 643 (3).png'
import threedimg3 from './../images/Rectangle 643 (4).png'
import threedimg4 from './../images/Rectangle 643 (5).png'
export const faqdata1 = [
  {
    id: 1,
    ques: "What all property types are there in  Zirakpur Project? ",
    ans: "uptown skylla offers ultra luxury large size 3 & 4 BHK Apartments and Low rise Independent Villa Floor",
  },
  {
    id: 2,
    ques: "What is the location of Sushma Belleza?",
    ans: "uptown skylla offers ultra luxury large size 3 & 4 BHK Apartments and Low rise Independent Villa Floor",
  },
  {
    id: 3,
    ques: "What all property types are there in  Zirakpur Project? ",
    ans: "uptown skylla offers ultra luxury large size 3 & 4 BHK Apartments and Low rise Independent Villa Floor",
  },
  {
    id: 4,
    ques: "Is Uptown Rera Approved ? ",
    ans: "uptown skylla offers ultra luxury large size 3 & 4 BHK Apartments and Low rise Independent Villa Floor",
  },
  {
    id: 5,
    ques: "Are the Bank Loan Facility Available on Uptown Project ?",
    ans: "uptown skylla offers ultra luxury large size 3 & 4 BHK Apartments and Low rise Independent Villa Floor",
  },
];
export const faqdata2 = [
  {
    id: 1,
    direction: "East",
    type : "type -1",
    SqFt1: "1980",
    SqFt2: "1682",
    carpetArea1:"1980",
    carpetArea2:"1682",
    balconyArea1:"305",
    balconyArea2:"911",
    wallArea1:"1980",
    wallArea2:"1682",
    commonArea1:"305",
    commonArea2:"911",
    twoDimg1:faq_img1,
    twoDimg2:"",
    threeDimg:threedimg1,

  },
  {
    id: 2,
    direction: "West",
    type : "type -2",
    SqFt1: "1980",
    SqFt2: "1682",
    carpetArea1:"1980",
    carpetArea2:"1682",
    balconyArea1:"305",
    balconyArea2:"911",
    wallArea1:"1980",
    wallArea2:"1682",
    commonArea1:"305",
    commonArea2:"911",
    twoDimg1:faq_img1,
    twoDimg2:"",
    threeDimg:threedimg2,
  },
  {
    id: 3,
    type : "type -1",
    direction: "East",
    SqFt1: "1980",
    SqFt2: "1682",
    carpetArea1:"1980",
    carpetArea2:"1682",
    balconyArea1:"305",
    balconyArea2:"911",
    wallArea1:"1980",
    wallArea2:"1682",
    commonArea1:"305",
    commonArea2:"911",
    twoDimg1:faq_img1,
    twoDimg2:"",
    threeDimg:threedimg3,
  },
  {
    id: 4,
    type : "type -2",
    direction: "West",
    SqFt1: "1980",
    SqFt2: "1682",
    carpetArea1:"1980",
    carpetArea2:"1682",
    balconyArea1:"305",
    balconyArea2:"911",
    wallArea1:"1980",
    wallArea2:"1682",
    commonArea1:"305",
    commonArea2:"911",
    twoDimg1:faq_img1,
    twoDimg2:"",
    threeDimg:threedimg4,
  },
];
